name: Integration Tests
on:
  pull_request: {}
  push:
    branches: main

# Cancel previous runs of this workflow when a new commit is added to the PR, branch or tag
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sovereign-integration-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SOVEREIGN_SDK_PRIVATE_SSH_KEY }}
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v15
        with:
          name: hermes-sdk
          extraPullNames: informal-sovereign
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: run integration tests
        env:
          RUST_BACKTRACE: 1
          CARGO_NET_GIT_FETCH_WITH_CLI: true
        run: |
            export WASM_FILE_PATH="$(nix build .#sov-celestia-cw --print-out-paths --no-link)/sov_celestia_client_cw.wasm"

            nix shell .#cargo-nextest .#protobuf .#ibc-go-v7-wasm-simapp .#celestia-app .#celestia-node .#sovereign-rollup -c \
              cargo nextest run -p hermes-sovereign-integration-tests \
              --test-threads=2 \
              --failure-output final